# Generated by Django 6.0.6 on 2026-06-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_creditnote_amount_remove_creditnote_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
