# Generated by Django 6.0.6 on 2026-06-19 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_lineitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineItem',
        ),
    ]
