# Generated by Django 6.0.6 on 2026-07-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_product_created_at_alter_creditnote_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('MPESA', 'M-Pesa')], default='MPESA', max_length=30),
        ),
    ]
