# Generated by Django 6.0.6 on 2026-07-03 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_payment_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
