# Generated by Django 6.0.6 on 2026-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'partial'), ('PAID', 'Fully Paid')], default='UNPAID', max_length=20),
        ),
    ]
